### ISSUE TITLE
[Documentation] Supported rails versions?

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-dsl-opal#5]
Hey there Andy,

The README here currently has this instruction:

    Install a Rails 5 gem:

    gem install rails -v5.2.6

If you look at https://rubygems.org/gems/rails/ then it lists rails version
7.0.0, as well as version 6.1.4.4 (released on December 15, 2021).

If you have some time in the future when looking at glimmer-dsl-opal,
could you perhaps mention whether the other two rails versions may
also work? Just so people can see whether they have to potentially
downgraded rails or e. g. mentioning this in the README whether
other rails version are supported by glimmer-dsl-opal.

That was my original use case (for the issue request) as well, since I had some
problems getting opal to work, so I thought I could try the glimmer-dsl-opal
instructions perhaps, then this may work. :)

Thank you for reading this issue request.

**Comment by AndyObtiva** [comment]
Only Rails 5 is supported at this time. I just added a missing setup step (mounting included Rails engine in `config/routes.rb`) that I forgot to recently include after adding to the project (but was included in the mentioned [Sample Glimmer DSL for Opal Rails App](https://github.com/AndyObtiva/sample-glimmer-dsl-opal-rails-app)). I am sorry about that. If you follow the setup instructions with Rails 5.2 now, they should work! Still, whenever you are in doubt, you could always check the [Sample Glimmer DSL for Opal Rails App](https://github.com/AndyObtiva/sample-glimmer-dsl-opal-rails-app) for a canonical working example since a working version of it is hosted on Heroku too to prove it works: https://sample-glimmer-dsl-opal-app.herokuapp.com/

Rails 6 was too problematic due to its bad default of using Webpacker, so I sort of skipped it while waiting for Rails 7, which defaults back to Sprockets (no more Webpack default, thank God!). 

I haven't had time to upgrade the project for Rails 7 yet, which was only released very recently. I'll keep this issue open until I've upgraded Glimmer DSL for Opal for Rails 7 and added working setup instructions for it.

Thank you for reporting and do not hesitate to ask me any further questions after you try it with Rails 5.2 for the time being.

**Comment by AndyObtiva** [comment]
OK, I just released [version 0.29.0](https://rubygems.org/gems/glimmer-dsl-opal/versions/0.29.0) with [support for Rails 7](https://github.com/AndyObtiva/glimmer-dsl-opal#rails-7) (also has a [Rails 7 Glimmer DSL for Opal sample project as a reference](https://github.com/AndyObtiva/sample-glimmer-dsl-opal-rails7-app)).

Please try the setup instructions and let me know if they worked for you or not. Your feedback is greatly appreciated.

I will spend some time in the future preparing instructions for Rails 6 too.

**Comment by AndyObtiva** [comment]
OK, I just added [instructions that work for Rails 6](https://github.com/AndyObtiva/glimmer-dsl-opal#rails-6) too (also has a [Rails 6 Glimmer DSL for Opal sample project as a reference](https://github.com/AndyObtiva/sample-glimmer-dsl-opal-rails6-app)).

I am closing this issue. 

If you encounter any issues, feel free to reopen this issue or create new ones.

Cheers!
